#!/bin/bash

echo "Setting up Vercel environment variables..."
echo ""
echo "You can set these variables in two ways:"
echo ""
echo "Option 1: Using Vercel CLI (run these commands):"
echo ""
echo "vercel env add SUPABASE_URL production"
echo "# Paste: https://vgtwkgckvryxbgujnqro.supabase.co"
echo ""
echo "vercel env add SUPABASE_ANON_KEY production"
echo "# Paste: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZndHdrZ2NrdnJ5eGJndWpucXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjkzMDMsImV4cCI6MjA2NTU0NTMwM30.pgOdbYD7heN3q2QM3E_yveAJMf8q6kKA2IGN9L2MdmI"
echo ""
echo "vercel env add SUPABASE_SERVICE_KEY production"
echo "# Paste: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZndHdrZ2NrdnJ5eGJndWpucXJvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTk2OTMwMywiZXhwIjoyMDY1NTQ1MzAzfQ.w_06qi4Gc_83_HygLFOXrWmAqcHDFX16zuNF-GshXkA"
echo ""
echo "Option 2: Using Vercel Dashboard (recommended):"
echo ""
echo "1. Go to: https://vercel.com/jacob-durrahs-projects/detroit-block-analytics/settings/environment-variables"
echo "2. Add these environment variables:"
echo ""
echo "SUPABASE_URL = https://vgtwkgckvryxbgujnqro.supabase.co"
echo "SUPABASE_ANON_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZndHdrZ2NrdnJ5eGJndWpucXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjkzMDMsImV4cCI6MjA2NTU0NTMwM30.pgOdbYD7heN3q2QM3E_yveAJMf8q6kKA2IGN9L2MdmI"
echo "SUPABASE_SERVICE_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZndHdrZ2NrdnJ5eGJndWpucXJvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTk2OTMwMywiZXhwIjoyMDY1NTQ1MzAzfQ.w_06qi4Gc_83_HygLFOXrWmAqcHDFX16zuNF-GshXkA"
echo ""
echo "3. Click 'Save' for each variable"
echo "4. Redeploy by running: vercel --prod"